# -*- coding: utf-8 -*-
"""full_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyBPsT75IWBpIms3jFagjAdDzXRwOUtj
"""

#small task done using numpy as np
import numpy as np
ab=np.array([1,5,12,13,15,20])
ak=np.array([4,8,12,16,20,24])

print("sum of given array              :     ", np.sum(ab))
print("Mean of given array             :     ", np.mean(ab))
print("Maximum number in  given array  :     ", np.max(ab))
print("minimum of given array          :     ", np.min(ab))

print("\n\n")



#manipulations

ab=np.insert(ab,1,2)
print("insert the value at index 1 value 2 : ",ab)

ab=np.append(ab,25)
print("after appending value 25            : ",ab)

ab=np.array([])
print("what if we want to clear the array  : ",ab)

print("\n\n\n")


#arithematic operation
ab=np.array([1,5,12,13,15,20])
ak=np.array([4,8,12,16,20,24])


print("sum is : ", ab+ak)
print("multiplication : ", ab*ak)
print("substraction   :" , ab-ak)
print("division       : ", ab/ak)
#print("power          : ", ab**ak)

print("\n\n")

sum=np.sum(ab)
print("sum is : ",sum)

subtract=np.subtract(ab,ab)
print("sub is : ",subtract)

mul=np.multiply(ab,ab)
print("sum is : ",mul)

divide=np.divide(ab,ab)
print("sum is : ",divide)

print(ab)

import numpy as np
az=np.array([1,2,3,4,5,6])

print(az)
print(np.sum(az))